---
# One time setup
# ansible-playbook ssh_setup.yml -i inventory --ask-pass
- hosts: all
  remote_user: "{{ vm_user }}"

  tasks:
  - name: Add SSH key to the remote host
    authorized_key: user="{{ vm_user }}" key="{{ lookup('file', '~/.ssh/id_lepus.pub') }}"
